name: get-repos-by-topics
author: gendloop
description: 'get-repos-by-topics'
inputs:
  token:
    description: 'Personal token'
    required: true
    default: ${{ github.token }}
  topics:
    description: 'topics'
    required: true
    default: ""

runs:
  using: 'composite'
  steps:
    - name: checkout-repo
      uses: actions/checkout@v3

    - name: get-repos-by-topics
      shell: bash
      run: |
        curl -H "Authorization: Brearer ${{ inputs.token }}" \
        "https://api.github.com/search/repositories?q=user:${{ github.repository_owner }}+${{ inputs.topics }}&per_page=100&page=1" \
        | jq '.items[] | {name: .name, description: .description}' > repos.json

    - name: git-push
      uses: gendloop/git-push@v1.0.0
      with:
        token: ${{ github.token }}
        commit: "chore: get repos by topics \\`${{ inputs.topics }}\\` "
