name: Get_Repos_By_Topics

permissions:
  contents: write
  actions: write

on: 
  workflow_dispatch:
  schedule:
    - cron: '35 18 * * 1'

jobs:
  template_name:
    runs-on: ubuntu-latest
    steps:
      - name: get-repos-by-topics
        uses: gendloop/get-repos-by-topics@main
        with: 
          token: ${{ secrets.GENDLOOP_ACCESS_TOKEN }}

      